/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParcelsIndexRouteImport } from './routes/parcels.index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as ShippingIdRouteImport } from './routes/shipping.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ParcelsIdRouteImport } from './routes/parcels.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminWarehouseRouteImport } from './routes/admin.warehouse'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as WarehouseIdQcRouteImport } from './routes/warehouse.$id.qc'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsIndexRoute = ParcelsIndexRouteImport.update({
  id: '/parcels/',
  path: '/parcels/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingIdRoute = ShippingIdRouteImport.update({
  id: '/shipping/$id',
  path: '/shipping/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsIdRoute = ParcelsIdRouteImport.update({
  id: '/parcels/$id',
  path: '/parcels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarehouseRoute = AdminWarehouseRouteImport.update({
  id: '/admin/warehouse',
  path: '/admin/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIdQcRoute = WarehouseIdQcRouteImport.update({
  id: '/$id/qc',
  path: '/$id/qc',
  getParentRoute: () => WarehouseRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/orders/$id': typeof OrdersIdRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shipping/$id': typeof ShippingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/parcels/': typeof ParcelsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/warehouse/$id/qc': typeof WarehouseIdQcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/orders/$id': typeof OrdersIdRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shipping/$id': typeof ShippingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/parcels': typeof ParcelsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/warehouse/$id/qc': typeof WarehouseIdQcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/affiliate': typeof AffiliateRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouse': typeof AdminWarehouseRoute
  '/orders/$id': typeof OrdersIdRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/shipping/$id': typeof ShippingIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/parcels/': typeof ParcelsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/warehouse/$id/qc': typeof WarehouseIdQcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/affiliate'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/favorites'
    | '/import'
    | '/login'
    | '/payment'
    | '/register'
    | '/search'
    | '/support'
    | '/verify-otp'
    | '/wallet'
    | '/warehouse'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warehouse'
    | '/orders/$id'
    | '/parcels/$id'
    | '/product/$id'
    | '/shipping/$id'
    | '/tracking/$id'
    | '/admin/'
    | '/orders/'
    | '/parcels/'
    | '/admin/orders/$id'
    | '/warehouse/$id/qc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/affiliate'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/favorites'
    | '/import'
    | '/login'
    | '/payment'
    | '/register'
    | '/search'
    | '/support'
    | '/verify-otp'
    | '/wallet'
    | '/warehouse'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warehouse'
    | '/orders/$id'
    | '/parcels/$id'
    | '/product/$id'
    | '/shipping/$id'
    | '/tracking/$id'
    | '/admin'
    | '/orders'
    | '/parcels'
    | '/admin/orders/$id'
    | '/warehouse/$id/qc'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/affiliate'
    | '/cart'
    | '/checkout'
    | '/dashboard'
    | '/favorites'
    | '/import'
    | '/login'
    | '/payment'
    | '/register'
    | '/search'
    | '/support'
    | '/verify-otp'
    | '/wallet'
    | '/warehouse'
    | '/admin/finance'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/warehouse'
    | '/orders/$id'
    | '/parcels/$id'
    | '/product/$id'
    | '/shipping/$id'
    | '/tracking/$id'
    | '/admin/'
    | '/orders/'
    | '/parcels/'
    | '/admin/orders/$id'
    | '/warehouse/$id/qc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AffiliateRoute: typeof AffiliateRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
  WarehouseRoute: typeof WarehouseRouteWithChildren
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehouseRoute: typeof AdminWarehouseRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ParcelsIdRoute: typeof ParcelsIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ShippingIdRoute: typeof ShippingIdRoute
  TrackingIdRoute: typeof TrackingIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ParcelsIndexRoute: typeof ParcelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels/': {
      id: '/parcels/'
      path: '/parcels'
      fullPath: '/parcels/'
      preLoaderRoute: typeof ParcelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping/$id': {
      id: '/shipping/$id'
      path: '/shipping/$id'
      fullPath: '/shipping/$id'
      preLoaderRoute: typeof ShippingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels/$id': {
      id: '/parcels/$id'
      path: '/parcels/$id'
      fullPath: '/parcels/$id'
      preLoaderRoute: typeof ParcelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warehouse': {
      id: '/admin/warehouse'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AdminWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/$id/qc': {
      id: '/warehouse/$id/qc'
      path: '/$id/qc'
      fullPath: '/warehouse/$id/qc'
      preLoaderRoute: typeof WarehouseIdQcRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface WarehouseRouteChildren {
  WarehouseIdQcRoute: typeof WarehouseIdQcRoute
}

const WarehouseRouteChildren: WarehouseRouteChildren = {
  WarehouseIdQcRoute: WarehouseIdQcRoute,
}

const WarehouseRouteWithChildren = WarehouseRoute._addFileChildren(
  WarehouseRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AffiliateRoute: AffiliateRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
  WarehouseRoute: WarehouseRouteWithChildren,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehouseRoute: AdminWarehouseRoute,
  OrdersIdRoute: OrdersIdRoute,
  ParcelsIdRoute: ParcelsIdRoute,
  ProductIdRoute: ProductIdRoute,
  ShippingIdRoute: ShippingIdRoute,
  TrackingIdRoute: TrackingIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ParcelsIndexRoute: ParcelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
